### ISSUE TITLE
macOS Sequoia benchmarks are published by CIS

### ISSUE THREAD

**Issue by mrmte** [Jamf-Concepts/jamf-compliance-editor#10]
macOS Sequoia benchmarks are published by CIS. Please update to ensure the tool includes the new benchmarks.

**Comment by golbiga** [comment]
This is covered by mSCP, which already has the latest benchmark included. If you choose Sequoia and then CIS Level 1 or 2, these should include the latest rules from 1.0.0 release from CIS.
