### ISSUE TITLE
Jamf Security CIS v1 wont upload to JAMF Pro

### ISSUE THREAD

**Issue by PhatAdam** [Jamf-Concepts/jamf-compliance-editor#14]
We have made zero changes to the CIS v1, on attempt to upload to our tenant we receive "The custom json schema must be manually uploaded via Jamf Pro"
![image](https://github.com/user-attachments/assets/f3fde82b-99e8-495b-ae42-0da2432b7ea3)

**Comment by PhatAdam** [comment]
sorry.  the docs covered this like -- 10 pages later.

**Comment by dmdhrumilmistry** [comment]
@PhatAdam how much time does it take to upload guidance to jamf pro server? I'm struggling while uploading. 

I have provided necessary permissions to my API role and client but get stuck every time I try to upload
