### ISSUE TITLE
Sonoma cis1 VoiceTriggerUserEnabled

### ISSUE THREAD

**Issue by chadmorales** [Jamf-Concepts/jamf-compliance-editor#3]
jce 1.3.1 (other versions not checked) is not generating a siri config for "Ensure Siri Listen For is Disabled"
<img width="432" alt="Screenshot 2024-08-30 at 2 19 25 PM" src="https://github.com/user-attachments/assets/d9d36399-b469-4646-b65a-31dfbe708412">
<img width="848" alt="Screenshot 2024-08-30 at 2 18 43 PM" src="https://github.com/user-attachments/assets/86cc5b2e-7db2-4f7b-894a-c19c4d7a42f4">

**Comment by golbiga** [comment]
This was a bug in mSCP where it should be `com.apple.Siri` and not `com.apple.siri`. This has been resolved, so should work just fine in JCE. Apologies for the delay in the response.
